import type { MigrationBuilder } from "node-pg-migrate";

/** Keeps an unmodeled Authors table outside the public schema for custom-table queries. */
export function up(b: MigrationBuilder): void {
  b.sql(`CREATE SCHEMA archive`);
  b.sql(
    `CREATE TABLE archive.authors (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name text NOT NULL)`,
  );
}
