module.exports = {
  branches: ["main"],
  plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    ["@semantic-release/npm", { pkgRoot: ".", npmPublish: false }],
    ["@semantic-release/npm", { npmPublish: false, pkgRoot: "packages/codegen" }],
    ["@semantic-release/npm", { npmPublish: false, pkgRoot: "packages/graphql-codegen" }],
    ["@semantic-release/npm", { npmPublish: false, pkgRoot: "packages/integration-tests" }],
    ["@semantic-release/npm", { npmPublish: false, pkgRoot: "packages/migration-utils" }],
    ["@semantic-release/npm", { npmPublish: false, pkgRoot: "packages/orm" }],
    ["@semantic-release/npm", { npmPublish: false, pkgRoot: "packages/tests/uuid-ids" }],
    ["@semantic-release/npm", { npmPublish: false, pkgRoot: "packages/utils" }],
    ["@semantic-release/exec", { publishCmd: "yarn npm publish", execCwd: "packages/codegen" }],
    ["@semantic-release/exec", { publishCmd: "yarn npm publish", execCwd: "packages/graphql-codegen" }],
    ["@semantic-release/exec", { publishCmd: "yarn npm publish", execCwd: "packages/migration-utils" }],
    ["@semantic-release/exec", { publishCmd: "yarn npm publish", execCwd: "packages/orm" }],
    ["@semantic-release/exec", { publishCmd: "yarn npm publish", execCwd: "packages/utils" }],
    "@semantic-release/github",
    ["@semantic-release/git", { assets: ["CHANGELOG.md", "package.json", "packages/*/package.json"] }],
  ],
};
