// Generated by joist-codegen (hash=b19cbd.461)
export * from "./Author.factories";
export * from "./AuthorStat.factories";
export * from "./Book.factories";
export * from "./BookAdvance.factories";
export * from "./BookReview.factories";
export * from "./Comment.factories";
export * from "./Critic.factories";
export * from "./CriticColumn.factories";
export * from "./Image.factories";
export * from "./Publisher.factories";
export * from "./Tag.factories";
