// Generated by joist-codegen (hash=c6dbe6)
export enum PublisherType {
  Small = "SMALL",
  Big = "BIG",
}

/** @ignore */
export type PublisherTypeDetails = { id: number; code: PublisherType; name: string };

const details: Record<PublisherType, PublisherTypeDetails> = {
  [PublisherType.Small]: { id: 1, code: PublisherType.Small, name: "Small" },
  [PublisherType.Big]: { id: 2, code: PublisherType.Big, name: "Big" },
};

/** @ignore */
export const PublisherTypes = {
  getByCode(code: PublisherType): PublisherTypeDetails {
    return details[code];
  },

  findByCode(code: string): PublisherTypeDetails | undefined {
    return details[code as PublisherType];
  },

  findById(id: number): PublisherTypeDetails | undefined {
    return Object.values(details).find((d) => d.id === id);
  },

  getValues(): ReadonlyArray<PublisherType> {
    return Object.values(PublisherType);
  },

  getDetails(): ReadonlyArray<PublisherTypeDetails> {
    return Object.values(details);
  },
};
